//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: northstar.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import Dispatch
import SwiftGRPC
import SwiftProtobuf

internal protocol NorthstarCloud_NorthStarServiceGetUserRescuePointsCall: ClientCallUnary {}

fileprivate final class NorthstarCloud_NorthStarServiceGetUserRescuePointsCallBase: ClientCallUnaryBase<NorthstarCloud_GetUserRescuePointsRequest, NorthstarCloud_GetUserRescuePointsReply>, NorthstarCloud_NorthStarServiceGetUserRescuePointsCall {
  override class var method: String { return "/northstar_cloud.NorthStarService/GetUserRescuePoints" }
}

internal protocol NorthstarCloud_NorthStarServiceAddUserCall: ClientCallUnary {}

fileprivate final class NorthstarCloud_NorthStarServiceAddUserCallBase: ClientCallUnaryBase<NorthstarCloud_AddUserRequest, NorthstarCloud_AddUserReply>, NorthstarCloud_NorthStarServiceAddUserCall {
  override class var method: String { return "/northstar_cloud.NorthStarService/AddUser" }
}

internal protocol NorthstarCloud_NorthStarServiceGetUserCall: ClientCallUnary {}

fileprivate final class NorthstarCloud_NorthStarServiceGetUserCallBase: ClientCallUnaryBase<NorthstarCloud_GetUserRequest, NorthstarCloud_GetUserReply>, NorthstarCloud_NorthStarServiceGetUserCall {
  override class var method: String { return "/northstar_cloud.NorthStarService/GetUser" }
}

internal protocol NorthstarCloud_NorthStarServiceUpdateUserCall: ClientCallUnary {}

fileprivate final class NorthstarCloud_NorthStarServiceUpdateUserCallBase: ClientCallUnaryBase<NorthstarCloud_AddUserRequest, NorthstarCloud_AddUserReply>, NorthstarCloud_NorthStarServiceUpdateUserCall {
  override class var method: String { return "/northstar_cloud.NorthStarService/UpdateUser" }
}

internal protocol NorthstarCloud_NorthStarServiceDeleteUserCall: ClientCallUnary {}

fileprivate final class NorthstarCloud_NorthStarServiceDeleteUserCallBase: ClientCallUnaryBase<NorthstarCloud_AddUserRequest, NorthstarCloud_AddUserReply>, NorthstarCloud_NorthStarServiceDeleteUserCall {
  override class var method: String { return "/northstar_cloud.NorthStarService/DeleteUser" }
}

internal protocol NorthstarCloud_NorthStarServiceUploadImageCall: ClientCallUnary {}

fileprivate final class NorthstarCloud_NorthStarServiceUploadImageCallBase: ClientCallUnaryBase<NorthstarCloud_UploadImageRequest, NorthstarCloud_UploadImageReply>, NorthstarCloud_NorthStarServiceUploadImageCall {
  override class var method: String { return "/northstar_cloud.NorthStarService/UploadImage" }
}

internal protocol NorthstarCloud_NorthStarServiceGetImageCall: ClientCallUnary {}

fileprivate final class NorthstarCloud_NorthStarServiceGetImageCallBase: ClientCallUnaryBase<NorthstarCloud_GetImageRequest, NorthstarCloud_GetImageReply>, NorthstarCloud_NorthStarServiceGetImageCall {
  override class var method: String { return "/northstar_cloud.NorthStarService/GetImage" }
}


/// Instantiate NorthstarCloud_NorthStarServiceServiceClient, then call methods of this protocol to make API calls.
internal protocol NorthstarCloud_NorthStarServiceService: ServiceClient {
  /// Synchronous. Unary.
  func getUserRescuePoints(_ request: NorthstarCloud_GetUserRescuePointsRequest) throws -> NorthstarCloud_GetUserRescuePointsReply
  /// Asynchronous. Unary.
  func getUserRescuePoints(_ request: NorthstarCloud_GetUserRescuePointsRequest, completion: @escaping (NorthstarCloud_GetUserRescuePointsReply?, CallResult) -> Void) throws -> NorthstarCloud_NorthStarServiceGetUserRescuePointsCall

  /// Synchronous. Unary.
  func addUser(_ request: NorthstarCloud_AddUserRequest) throws -> NorthstarCloud_AddUserReply
  /// Asynchronous. Unary.
  func addUser(_ request: NorthstarCloud_AddUserRequest, completion: @escaping (NorthstarCloud_AddUserReply?, CallResult) -> Void) throws -> NorthstarCloud_NorthStarServiceAddUserCall

  /// Synchronous. Unary.
  func getUser(_ request: NorthstarCloud_GetUserRequest) throws -> NorthstarCloud_GetUserReply
  /// Asynchronous. Unary.
  func getUser(_ request: NorthstarCloud_GetUserRequest, completion: @escaping (NorthstarCloud_GetUserReply?, CallResult) -> Void) throws -> NorthstarCloud_NorthStarServiceGetUserCall

  /// Synchronous. Unary.
  func updateUser(_ request: NorthstarCloud_AddUserRequest) throws -> NorthstarCloud_AddUserReply
  /// Asynchronous. Unary.
  func updateUser(_ request: NorthstarCloud_AddUserRequest, completion: @escaping (NorthstarCloud_AddUserReply?, CallResult) -> Void) throws -> NorthstarCloud_NorthStarServiceUpdateUserCall

  /// Synchronous. Unary.
  func deleteUser(_ request: NorthstarCloud_AddUserRequest) throws -> NorthstarCloud_AddUserReply
  /// Asynchronous. Unary.
  func deleteUser(_ request: NorthstarCloud_AddUserRequest, completion: @escaping (NorthstarCloud_AddUserReply?, CallResult) -> Void) throws -> NorthstarCloud_NorthStarServiceDeleteUserCall

  /// Synchronous. Unary.
  func uploadImage(_ request: NorthstarCloud_UploadImageRequest) throws -> NorthstarCloud_UploadImageReply
  /// Asynchronous. Unary.
  func uploadImage(_ request: NorthstarCloud_UploadImageRequest, completion: @escaping (NorthstarCloud_UploadImageReply?, CallResult) -> Void) throws -> NorthstarCloud_NorthStarServiceUploadImageCall

  /// Synchronous. Unary.
  func getImage(_ request: NorthstarCloud_GetImageRequest) throws -> NorthstarCloud_GetImageReply
  /// Asynchronous. Unary.
  func getImage(_ request: NorthstarCloud_GetImageRequest, completion: @escaping (NorthstarCloud_GetImageReply?, CallResult) -> Void) throws -> NorthstarCloud_NorthStarServiceGetImageCall

}

internal final class NorthstarCloud_NorthStarServiceServiceClient: ServiceClientBase, NorthstarCloud_NorthStarServiceService {
  /// Synchronous. Unary.
  internal func getUserRescuePoints(_ request: NorthstarCloud_GetUserRescuePointsRequest) throws -> NorthstarCloud_GetUserRescuePointsReply {
    return try NorthstarCloud_NorthStarServiceGetUserRescuePointsCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func getUserRescuePoints(_ request: NorthstarCloud_GetUserRescuePointsRequest, completion: @escaping (NorthstarCloud_GetUserRescuePointsReply?, CallResult) -> Void) throws -> NorthstarCloud_NorthStarServiceGetUserRescuePointsCall {
    return try NorthstarCloud_NorthStarServiceGetUserRescuePointsCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func addUser(_ request: NorthstarCloud_AddUserRequest) throws -> NorthstarCloud_AddUserReply {
    return try NorthstarCloud_NorthStarServiceAddUserCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func addUser(_ request: NorthstarCloud_AddUserRequest, completion: @escaping (NorthstarCloud_AddUserReply?, CallResult) -> Void) throws -> NorthstarCloud_NorthStarServiceAddUserCall {
    return try NorthstarCloud_NorthStarServiceAddUserCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func getUser(_ request: NorthstarCloud_GetUserRequest) throws -> NorthstarCloud_GetUserReply {
    return try NorthstarCloud_NorthStarServiceGetUserCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func getUser(_ request: NorthstarCloud_GetUserRequest, completion: @escaping (NorthstarCloud_GetUserReply?, CallResult) -> Void) throws -> NorthstarCloud_NorthStarServiceGetUserCall {
    return try NorthstarCloud_NorthStarServiceGetUserCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func updateUser(_ request: NorthstarCloud_AddUserRequest) throws -> NorthstarCloud_AddUserReply {
    return try NorthstarCloud_NorthStarServiceUpdateUserCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func updateUser(_ request: NorthstarCloud_AddUserRequest, completion: @escaping (NorthstarCloud_AddUserReply?, CallResult) -> Void) throws -> NorthstarCloud_NorthStarServiceUpdateUserCall {
    return try NorthstarCloud_NorthStarServiceUpdateUserCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func deleteUser(_ request: NorthstarCloud_AddUserRequest) throws -> NorthstarCloud_AddUserReply {
    return try NorthstarCloud_NorthStarServiceDeleteUserCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func deleteUser(_ request: NorthstarCloud_AddUserRequest, completion: @escaping (NorthstarCloud_AddUserReply?, CallResult) -> Void) throws -> NorthstarCloud_NorthStarServiceDeleteUserCall {
    return try NorthstarCloud_NorthStarServiceDeleteUserCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func uploadImage(_ request: NorthstarCloud_UploadImageRequest) throws -> NorthstarCloud_UploadImageReply {
    return try NorthstarCloud_NorthStarServiceUploadImageCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func uploadImage(_ request: NorthstarCloud_UploadImageRequest, completion: @escaping (NorthstarCloud_UploadImageReply?, CallResult) -> Void) throws -> NorthstarCloud_NorthStarServiceUploadImageCall {
    return try NorthstarCloud_NorthStarServiceUploadImageCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

  /// Synchronous. Unary.
  internal func getImage(_ request: NorthstarCloud_GetImageRequest) throws -> NorthstarCloud_GetImageReply {
    return try NorthstarCloud_NorthStarServiceGetImageCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func getImage(_ request: NorthstarCloud_GetImageRequest, completion: @escaping (NorthstarCloud_GetImageReply?, CallResult) -> Void) throws -> NorthstarCloud_NorthStarServiceGetImageCall {
    return try NorthstarCloud_NorthStarServiceGetImageCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

}

/// To build a server, implement a class that conforms to this protocol.
/// If one of the methods returning `ServerStatus?` returns nil,
/// it is expected that you have already returned a status to the client by means of `session.close`.
internal protocol NorthstarCloud_NorthStarServiceProvider: ServiceProvider {
  func getUserRescuePoints(request: NorthstarCloud_GetUserRescuePointsRequest, session: NorthstarCloud_NorthStarServiceGetUserRescuePointsSession) throws -> NorthstarCloud_GetUserRescuePointsReply
  func addUser(request: NorthstarCloud_AddUserRequest, session: NorthstarCloud_NorthStarServiceAddUserSession) throws -> NorthstarCloud_AddUserReply
  func getUser(request: NorthstarCloud_GetUserRequest, session: NorthstarCloud_NorthStarServiceGetUserSession) throws -> NorthstarCloud_GetUserReply
  func updateUser(request: NorthstarCloud_AddUserRequest, session: NorthstarCloud_NorthStarServiceUpdateUserSession) throws -> NorthstarCloud_AddUserReply
  func deleteUser(request: NorthstarCloud_AddUserRequest, session: NorthstarCloud_NorthStarServiceDeleteUserSession) throws -> NorthstarCloud_AddUserReply
  func uploadImage(request: NorthstarCloud_UploadImageRequest, session: NorthstarCloud_NorthStarServiceUploadImageSession) throws -> NorthstarCloud_UploadImageReply
  func getImage(request: NorthstarCloud_GetImageRequest, session: NorthstarCloud_NorthStarServiceGetImageSession) throws -> NorthstarCloud_GetImageReply
}

extension NorthstarCloud_NorthStarServiceProvider {
  internal var serviceName: String { return "northstar_cloud.NorthStarService" }

  /// Determines and calls the appropriate request handler, depending on the request's method.
  /// Throws `HandleMethodError.unknownMethod` for methods not handled by this service.
  internal func handleMethod(_ method: String, handler: Handler) throws -> ServerStatus? {
    switch method {
    case "/northstar_cloud.NorthStarService/GetUserRescuePoints":
      return try NorthstarCloud_NorthStarServiceGetUserRescuePointsSessionBase(
        handler: handler,
        providerBlock: { try self.getUserRescuePoints(request: $0, session: $1 as! NorthstarCloud_NorthStarServiceGetUserRescuePointsSessionBase) })
          .run()
    case "/northstar_cloud.NorthStarService/AddUser":
      return try NorthstarCloud_NorthStarServiceAddUserSessionBase(
        handler: handler,
        providerBlock: { try self.addUser(request: $0, session: $1 as! NorthstarCloud_NorthStarServiceAddUserSessionBase) })
          .run()
    case "/northstar_cloud.NorthStarService/GetUser":
      return try NorthstarCloud_NorthStarServiceGetUserSessionBase(
        handler: handler,
        providerBlock: { try self.getUser(request: $0, session: $1 as! NorthstarCloud_NorthStarServiceGetUserSessionBase) })
          .run()
    case "/northstar_cloud.NorthStarService/UpdateUser":
      return try NorthstarCloud_NorthStarServiceUpdateUserSessionBase(
        handler: handler,
        providerBlock: { try self.updateUser(request: $0, session: $1 as! NorthstarCloud_NorthStarServiceUpdateUserSessionBase) })
          .run()
    case "/northstar_cloud.NorthStarService/DeleteUser":
      return try NorthstarCloud_NorthStarServiceDeleteUserSessionBase(
        handler: handler,
        providerBlock: { try self.deleteUser(request: $0, session: $1 as! NorthstarCloud_NorthStarServiceDeleteUserSessionBase) })
          .run()
    case "/northstar_cloud.NorthStarService/UploadImage":
      return try NorthstarCloud_NorthStarServiceUploadImageSessionBase(
        handler: handler,
        providerBlock: { try self.uploadImage(request: $0, session: $1 as! NorthstarCloud_NorthStarServiceUploadImageSessionBase) })
          .run()
    case "/northstar_cloud.NorthStarService/GetImage":
      return try NorthstarCloud_NorthStarServiceGetImageSessionBase(
        handler: handler,
        providerBlock: { try self.getImage(request: $0, session: $1 as! NorthstarCloud_NorthStarServiceGetImageSessionBase) })
          .run()
    default:
      throw HandleMethodError.unknownMethod
    }
  }
}

internal protocol NorthstarCloud_NorthStarServiceGetUserRescuePointsSession: ServerSessionUnary {}

fileprivate final class NorthstarCloud_NorthStarServiceGetUserRescuePointsSessionBase: ServerSessionUnaryBase<NorthstarCloud_GetUserRescuePointsRequest, NorthstarCloud_GetUserRescuePointsReply>, NorthstarCloud_NorthStarServiceGetUserRescuePointsSession {}

internal protocol NorthstarCloud_NorthStarServiceAddUserSession: ServerSessionUnary {}

fileprivate final class NorthstarCloud_NorthStarServiceAddUserSessionBase: ServerSessionUnaryBase<NorthstarCloud_AddUserRequest, NorthstarCloud_AddUserReply>, NorthstarCloud_NorthStarServiceAddUserSession {}

internal protocol NorthstarCloud_NorthStarServiceGetUserSession: ServerSessionUnary {}

fileprivate final class NorthstarCloud_NorthStarServiceGetUserSessionBase: ServerSessionUnaryBase<NorthstarCloud_GetUserRequest, NorthstarCloud_GetUserReply>, NorthstarCloud_NorthStarServiceGetUserSession {}

internal protocol NorthstarCloud_NorthStarServiceUpdateUserSession: ServerSessionUnary {}

fileprivate final class NorthstarCloud_NorthStarServiceUpdateUserSessionBase: ServerSessionUnaryBase<NorthstarCloud_AddUserRequest, NorthstarCloud_AddUserReply>, NorthstarCloud_NorthStarServiceUpdateUserSession {}

internal protocol NorthstarCloud_NorthStarServiceDeleteUserSession: ServerSessionUnary {}

fileprivate final class NorthstarCloud_NorthStarServiceDeleteUserSessionBase: ServerSessionUnaryBase<NorthstarCloud_AddUserRequest, NorthstarCloud_AddUserReply>, NorthstarCloud_NorthStarServiceDeleteUserSession {}

internal protocol NorthstarCloud_NorthStarServiceUploadImageSession: ServerSessionUnary {}

fileprivate final class NorthstarCloud_NorthStarServiceUploadImageSessionBase: ServerSessionUnaryBase<NorthstarCloud_UploadImageRequest, NorthstarCloud_UploadImageReply>, NorthstarCloud_NorthStarServiceUploadImageSession {}

internal protocol NorthstarCloud_NorthStarServiceGetImageSession: ServerSessionUnary {}

fileprivate final class NorthstarCloud_NorthStarServiceGetImageSessionBase: ServerSessionUnaryBase<NorthstarCloud_GetImageRequest, NorthstarCloud_GetImageReply>, NorthstarCloud_NorthStarServiceGetImageSession {}

