# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import northstar_pb2 as northstar__pb2


class NorthStarServiceStub(object):
  """The `NorthStar` provides APIs.

  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetUserRescuePoints = channel.unary_unary(
        '/northstar_cloud.NorthStarService/GetUserRescuePoints',
        request_serializer=northstar__pb2.GetUserRescuePointsRequest.SerializeToString,
        response_deserializer=northstar__pb2.GetUserRescuePointsReply.FromString,
        )
    self.AddUser = channel.unary_unary(
        '/northstar_cloud.NorthStarService/AddUser',
        request_serializer=northstar__pb2.AddUserRequest.SerializeToString,
        response_deserializer=northstar__pb2.AddUserReply.FromString,
        )
    self.GetUser = channel.unary_unary(
        '/northstar_cloud.NorthStarService/GetUser',
        request_serializer=northstar__pb2.GetUserRequest.SerializeToString,
        response_deserializer=northstar__pb2.GetUserReply.FromString,
        )
    self.UpdateUser = channel.unary_unary(
        '/northstar_cloud.NorthStarService/UpdateUser',
        request_serializer=northstar__pb2.AddUserRequest.SerializeToString,
        response_deserializer=northstar__pb2.AddUserReply.FromString,
        )
    self.DeleteUser = channel.unary_unary(
        '/northstar_cloud.NorthStarService/DeleteUser',
        request_serializer=northstar__pb2.AddUserRequest.SerializeToString,
        response_deserializer=northstar__pb2.AddUserReply.FromString,
        )
    self.UploadImage = channel.unary_unary(
        '/northstar_cloud.NorthStarService/UploadImage',
        request_serializer=northstar__pb2.UploadImageRequest.SerializeToString,
        response_deserializer=northstar__pb2.UploadImageReply.FromString,
        )
    self.GetImage = channel.unary_unary(
        '/northstar_cloud.NorthStarService/GetImage',
        request_serializer=northstar__pb2.GetImageRequest.SerializeToString,
        response_deserializer=northstar__pb2.GetImageReply.FromString,
        )


class NorthStarServiceServicer(object):
  """The `NorthStar` provides APIs.

  """

  def GetUserRescuePoints(self, request, context):
    """User activity
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UploadImage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetImage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NorthStarServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetUserRescuePoints': grpc.unary_unary_rpc_method_handler(
          servicer.GetUserRescuePoints,
          request_deserializer=northstar__pb2.GetUserRescuePointsRequest.FromString,
          response_serializer=northstar__pb2.GetUserRescuePointsReply.SerializeToString,
      ),
      'AddUser': grpc.unary_unary_rpc_method_handler(
          servicer.AddUser,
          request_deserializer=northstar__pb2.AddUserRequest.FromString,
          response_serializer=northstar__pb2.AddUserReply.SerializeToString,
      ),
      'GetUser': grpc.unary_unary_rpc_method_handler(
          servicer.GetUser,
          request_deserializer=northstar__pb2.GetUserRequest.FromString,
          response_serializer=northstar__pb2.GetUserReply.SerializeToString,
      ),
      'UpdateUser': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateUser,
          request_deserializer=northstar__pb2.AddUserRequest.FromString,
          response_serializer=northstar__pb2.AddUserReply.SerializeToString,
      ),
      'DeleteUser': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteUser,
          request_deserializer=northstar__pb2.AddUserRequest.FromString,
          response_serializer=northstar__pb2.AddUserReply.SerializeToString,
      ),
      'UploadImage': grpc.unary_unary_rpc_method_handler(
          servicer.UploadImage,
          request_deserializer=northstar__pb2.UploadImageRequest.FromString,
          response_serializer=northstar__pb2.UploadImageReply.SerializeToString,
      ),
      'GetImage': grpc.unary_unary_rpc_method_handler(
          servicer.GetImage,
          request_deserializer=northstar__pb2.GetImageRequest.FromString,
          response_serializer=northstar__pb2.GetImageReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'northstar_cloud.NorthStarService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
