---
apiVersion: v1
kind: ConfigMap
metadata:
  name: detective-api-config
  namespace: default
data:
  config: |
    {
      "bind" : "[::]:50051",
      "default_local_address" : "localhost:50051"
    }
