---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: northstar-cloud
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: northstar-cloud
    spec:
      containers:
        - name: northstar-cloud
          stdin: true
          tty: true
          args:
            - northstar-cloud
          image: northstar-cloud:latest
          ports:
            - name: api-pod-port
              containerPort: 50051
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config
              readOnly: true
              mountPath: /etc/config
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: detective-api-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: northstar-cloud
  name: northstar-cloud
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: api-pod-port
      port: 50051
      targetPort: api-pod-port
  selector:
    app: northstar-cloud
---
