apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: northstar-weather-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: northstar-weather-service
    spec:
      containers:
        - name: northstar-weather-service
          stdin: true
          tty: true
          args:
            - northstar-weather
          image: northstar-cloud:latest
          env:
            - name: DB_DEPLOYMENT
              value: "minikube"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: northstar-service-config
              readOnly: true
              mountPath: /etc/northstar-service-config
      restartPolicy: Always
      volumes:
        - name: northstar-service-config
          configMap:
            name: northstar-service-config