---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: northstar-user-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: northstar-api-service
    spec:
      containers:
        - name: northstar-api-service
          stdin: true
          tty: true
          args:
            - northstar-cloud
          image: northstar-cloud:latest
          env:
            - name: DB_DEPLOYMENT
              value: "minikube"
          ports:
            - name: api-pod-port
              containerPort: 50051
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: northstar-service-config
              readOnly: true
              mountPath: /etc/northstar-service-config
      restartPolicy: Always
      volumes:
        - name: northstar-service-config
          configMap:
            name: northstar-service-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: northstar-api-service
  name: northstar-api-service
spec:
  type: NodePort
  ports:
    - name: api-pod-port
      port: 50051
      targetPort: 50051
      nodePort: 30036
      protocol: TCP
  selector:
    name: northstar-api-service
---