# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: northstar.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='northstar.proto',
  package='northstar_cloud',
  syntax='proto3',
  serialized_pb=_b('\n\x0fnorthstar.proto\x12\x0fnorthstar_cloud\"-\n\x06LatLng\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\"*\n\nHealthInfo\x12\x1c\n\x14need_medical_support\x18\x01 \x01(\x08\"\x90\x03\n\x04User\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x11\n\tuser_name\x18\x02 \x01(\t\x12\x12\n\nfirst_name\x18\x03 \x01(\t\x12\x11\n\tlast_name\x18\x04 \x01(\t\x12\x14\n\x0cphone_number\x18\x05 \x01(\t\x12\x14\n\x0chome_address\x18\x06 \x01(\t\x12\x15\n\remail_address\x18\x07 \x01(\t\x12\x16\n\x0eoffice_address\x18\x08 \x01(\t\x12\x0e\n\x06\x61pp_id\x18\t \x01(\t\x12\x10\n\x08\x61pp_type\x18\n \x01(\t\x12\x14\n\x0clast_updated\x18\x0b \x01(\t\x12\x12\n\ncreated_at\x18\x0c \x01(\t\x12\x31\n\x10\x63urrent_location\x18\r \x01(\x0b\x32\x17.northstar_cloud.LatLng\x12\x30\n\x0bhealth_info\x18\x0e \x01(\x0b\x32\x1b.northstar_cloud.HealthInfo\x12\x31\n\x10rescue_locations\x18\x0f \x03(\x0b\x32\x17.northstar_cloud.LatLng\"5\n\x0e\x41\x64\x64UserRequest\x12#\n\x04user\x18\x01 \x01(\x0b\x32\x15.northstar_cloud.User\"\x1f\n\x0c\x41\x64\x64UserReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\"A\n\x1aGetUserRescuePointsRequest\x12#\n\x04user\x18\x01 \x01(\x0b\x32\x15.northstar_cloud.User\"M\n\x18GetUserRescuePointsReply\x12\x31\n\x10rescue_locations\x18\x01 \x03(\x0b\x32\x17.northstar_cloud.LatLng2\xe8\x02\n\x10NorthStarService\x12m\n\x13GetUserRescuePoints\x12+.northstar_cloud.GetUserRescuePointsRequest\x1a).northstar_cloud.GetUserRescuePointsReply\x12I\n\x07\x41\x64\x64User\x12\x1f.northstar_cloud.AddUserRequest\x1a\x1d.northstar_cloud.AddUserReply\x12L\n\nUpdateUser\x12\x1f.northstar_cloud.AddUserRequest\x1a\x1d.northstar_cloud.AddUserReply\x12L\n\nDeleteUser\x12\x1f.northstar_cloud.AddUserRequest\x1a\x1d.northstar_cloud.AddUserReplyb\x06proto3')
)




_LATLNG = _descriptor.Descriptor(
  name='LatLng',
  full_name='northstar_cloud.LatLng',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='northstar_cloud.LatLng.latitude', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='northstar_cloud.LatLng.longitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=81,
)


_HEALTHINFO = _descriptor.Descriptor(
  name='HealthInfo',
  full_name='northstar_cloud.HealthInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='need_medical_support', full_name='northstar_cloud.HealthInfo.need_medical_support', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=125,
)


_USER = _descriptor.Descriptor(
  name='User',
  full_name='northstar_cloud.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='northstar_cloud.User.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_name', full_name='northstar_cloud.User.user_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='first_name', full_name='northstar_cloud.User.first_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='northstar_cloud.User.last_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='phone_number', full_name='northstar_cloud.User.phone_number', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='home_address', full_name='northstar_cloud.User.home_address', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email_address', full_name='northstar_cloud.User.email_address', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='office_address', full_name='northstar_cloud.User.office_address', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='app_id', full_name='northstar_cloud.User.app_id', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='app_type', full_name='northstar_cloud.User.app_type', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_updated', full_name='northstar_cloud.User.last_updated', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='northstar_cloud.User.created_at', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='current_location', full_name='northstar_cloud.User.current_location', index=12,
      number=13, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='health_info', full_name='northstar_cloud.User.health_info', index=13,
      number=14, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rescue_locations', full_name='northstar_cloud.User.rescue_locations', index=14,
      number=15, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=528,
)


_ADDUSERREQUEST = _descriptor.Descriptor(
  name='AddUserRequest',
  full_name='northstar_cloud.AddUserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='northstar_cloud.AddUserRequest.user', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=530,
  serialized_end=583,
)


_ADDUSERREPLY = _descriptor.Descriptor(
  name='AddUserReply',
  full_name='northstar_cloud.AddUserReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='northstar_cloud.AddUserReply.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=585,
  serialized_end=616,
)


_GETUSERRESCUEPOINTSREQUEST = _descriptor.Descriptor(
  name='GetUserRescuePointsRequest',
  full_name='northstar_cloud.GetUserRescuePointsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='northstar_cloud.GetUserRescuePointsRequest.user', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=618,
  serialized_end=683,
)


_GETUSERRESCUEPOINTSREPLY = _descriptor.Descriptor(
  name='GetUserRescuePointsReply',
  full_name='northstar_cloud.GetUserRescuePointsReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rescue_locations', full_name='northstar_cloud.GetUserRescuePointsReply.rescue_locations', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=685,
  serialized_end=762,
)

_USER.fields_by_name['current_location'].message_type = _LATLNG
_USER.fields_by_name['health_info'].message_type = _HEALTHINFO
_USER.fields_by_name['rescue_locations'].message_type = _LATLNG
_ADDUSERREQUEST.fields_by_name['user'].message_type = _USER
_GETUSERRESCUEPOINTSREQUEST.fields_by_name['user'].message_type = _USER
_GETUSERRESCUEPOINTSREPLY.fields_by_name['rescue_locations'].message_type = _LATLNG
DESCRIPTOR.message_types_by_name['LatLng'] = _LATLNG
DESCRIPTOR.message_types_by_name['HealthInfo'] = _HEALTHINFO
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['AddUserRequest'] = _ADDUSERREQUEST
DESCRIPTOR.message_types_by_name['AddUserReply'] = _ADDUSERREPLY
DESCRIPTOR.message_types_by_name['GetUserRescuePointsRequest'] = _GETUSERRESCUEPOINTSREQUEST
DESCRIPTOR.message_types_by_name['GetUserRescuePointsReply'] = _GETUSERRESCUEPOINTSREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LatLng = _reflection.GeneratedProtocolMessageType('LatLng', (_message.Message,), dict(
  DESCRIPTOR = _LATLNG,
  __module__ = 'northstar_pb2'
  # @@protoc_insertion_point(class_scope:northstar_cloud.LatLng)
  ))
_sym_db.RegisterMessage(LatLng)

HealthInfo = _reflection.GeneratedProtocolMessageType('HealthInfo', (_message.Message,), dict(
  DESCRIPTOR = _HEALTHINFO,
  __module__ = 'northstar_pb2'
  # @@protoc_insertion_point(class_scope:northstar_cloud.HealthInfo)
  ))
_sym_db.RegisterMessage(HealthInfo)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), dict(
  DESCRIPTOR = _USER,
  __module__ = 'northstar_pb2'
  # @@protoc_insertion_point(class_scope:northstar_cloud.User)
  ))
_sym_db.RegisterMessage(User)

AddUserRequest = _reflection.GeneratedProtocolMessageType('AddUserRequest', (_message.Message,), dict(
  DESCRIPTOR = _ADDUSERREQUEST,
  __module__ = 'northstar_pb2'
  # @@protoc_insertion_point(class_scope:northstar_cloud.AddUserRequest)
  ))
_sym_db.RegisterMessage(AddUserRequest)

AddUserReply = _reflection.GeneratedProtocolMessageType('AddUserReply', (_message.Message,), dict(
  DESCRIPTOR = _ADDUSERREPLY,
  __module__ = 'northstar_pb2'
  # @@protoc_insertion_point(class_scope:northstar_cloud.AddUserReply)
  ))
_sym_db.RegisterMessage(AddUserReply)

GetUserRescuePointsRequest = _reflection.GeneratedProtocolMessageType('GetUserRescuePointsRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETUSERRESCUEPOINTSREQUEST,
  __module__ = 'northstar_pb2'
  # @@protoc_insertion_point(class_scope:northstar_cloud.GetUserRescuePointsRequest)
  ))
_sym_db.RegisterMessage(GetUserRescuePointsRequest)

GetUserRescuePointsReply = _reflection.GeneratedProtocolMessageType('GetUserRescuePointsReply', (_message.Message,), dict(
  DESCRIPTOR = _GETUSERRESCUEPOINTSREPLY,
  __module__ = 'northstar_pb2'
  # @@protoc_insertion_point(class_scope:northstar_cloud.GetUserRescuePointsReply)
  ))
_sym_db.RegisterMessage(GetUserRescuePointsReply)



_NORTHSTARSERVICE = _descriptor.ServiceDescriptor(
  name='NorthStarService',
  full_name='northstar_cloud.NorthStarService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=765,
  serialized_end=1125,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetUserRescuePoints',
    full_name='northstar_cloud.NorthStarService.GetUserRescuePoints',
    index=0,
    containing_service=None,
    input_type=_GETUSERRESCUEPOINTSREQUEST,
    output_type=_GETUSERRESCUEPOINTSREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AddUser',
    full_name='northstar_cloud.NorthStarService.AddUser',
    index=1,
    containing_service=None,
    input_type=_ADDUSERREQUEST,
    output_type=_ADDUSERREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateUser',
    full_name='northstar_cloud.NorthStarService.UpdateUser',
    index=2,
    containing_service=None,
    input_type=_ADDUSERREQUEST,
    output_type=_ADDUSERREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteUser',
    full_name='northstar_cloud.NorthStarService.DeleteUser',
    index=3,
    containing_service=None,
    input_type=_ADDUSERREQUEST,
    output_type=_ADDUSERREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_NORTHSTARSERVICE)

DESCRIPTOR.services_by_name['NorthStarService'] = _NORTHSTARSERVICE

# @@protoc_insertion_point(module_scope)
